name: GravityGun
version: ${project.version}
api-version: 1.14
main: com.darkender.plugins.gravitygun.GravityGun
author: Techdoodle
commands:
  gravitygun:
    aliases:
      - gg
    permission: gravitygun.cmd
permissions:
  gravitygun.pickup.block:
    default: true
  gravitygun.pickup.entity:
    default: true
  gravitygun.repelheld:
    default: true
  gravitygun.repelarea:
    default: true
  gravitygun.cmd.get:
    default: op
  gravitygun.cmd.reload:
    default: op